name: Publish Major Version Update

on:
  workflow_dispatch:

jobs:
  build:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure all tags are fetched

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PASSWORD }}  # Ensure you have this secret set

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./ReceiptBuilder.Server/Dockerfile  # Update path to your Dockerfile
          push: true
          tags: ghcr.io/christopher-dev/receiptmarkuplanguage:latest
          build-args: |
            BUILD_CONFIGURATION=Release

      - name: Logout from GitHub Container Registry
        run: docker logout ghcr.io
